include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:
    always_use_package_imports: true
    unnecessary_brace_in_string_interps: false
    avoid_single_cascade_in_expression_statements: false
