name: flutter_extensions
description: It adds utility extensions to the flutter classes and adds some utility classes.
version: 2.1.0
author: BreX900
homepage: https://github.com/BreX900/dart_extensions/tree/master/flutter_extensions

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  pure_extensions: ^2.1.0
#    path: ../pure_extensions

  rxdart: ^0.24.1

  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
