name: flutter_extensions
description: A new Flutter project.
version: 2.0.0
author: BreX900
homepage: https://github.com/BreX900/flutter_extensions

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  pure_extensions:
    path: ../pure_extensions

  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
