name: pure_extensions
description: It adds utility extensions to the dart classes and adds some utility classes, builders.
version: 5.0.0
homepage: https://github.com/BreX900/dart_extensions/tree/master/pure_extensions

# dart pub publish --dry-run

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  rational: ^2.1.0

  rxdart: ^0.27.2

  collection: ^1.15.0

dev_dependencies:
  test:

  mek_lints: ^1.0.0
