name: pure_extensions
description: It adds utility extensions to the dart classes and adds some utility classes, builders.
version: 4.0.1
homepage: https://github.com/BreX900/dart_extensions/tree/master/pure_extensions

# dart pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rational: ^1.2.0
  path: ^1.8.0

  built_value: ^8.1.0
  built_collection: ^5.1.0
  rxdart: ^0.27.2

  time: ^2.0.0
  collection: ^1.15.0
  recase: ^4.0.0

dev_dependencies:
  test:

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner:
  built_value_generator: ^8.1.2

  lints: