name: pure_extensions
description: It adds utility extensions to the dart classes and adds some utility classes, builders.
version: 2.1.0
author: BreX900
homepage: https://github.com/BreX900/dart_extensions/tree/master/pure_extensions

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rational: ^0.3.8
  basic_utils: ^2.7.1
  path: ^1.7.0
  meta: ^1.2.4

  built_value: ^7.1.0
  built_collection: ^4.3.2
  rxdart: ^0.24.1

  time: ^1.4.0

dev_dependencies:
  test: ^1.15.7

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: 1.10.2
  built_value_generator: ^7.1.0