name: pure_extensions
description: It adds utility extensions to the dart classes and adds some utility classes.
version: 2.0.3
author: BreX900
homepage: https://github.com/BreX900/dart_extensions/tree/master/pure_extensions

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  tinycolor: ^1.0.3
  rational: ^0.3.8
  basic_utils: ^2.6.3
  path: ^1.7.0
  meta: ^1.2.4

  built_value: ^7.1.0
  built_collection: ^4.3.2
  rxdart: ^0.24.1

  time: ^1.4.0