name: pure_extensions
description: It adds utility extensions to the dart classes and adds some utility classes, builders.
version: 3.0.0
author: BreX900
homepage: https://github.com/BreX900/dart_extensions/tree/master/pure_extensions

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rational: ^1.1.0+1
  basic_utils: ^3.0.2
  path: ^1.8.0
  meta: ^1.3.0

  built_value: ^8.0.5
  built_collection: ^5.0.0
  rxdart: ^0.26.0

  time: ^2.0.0

dev_dependencies:
  test: ^1.17.2

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^1.0.0
  built_value_generator: ^8.0.5